---

- include: install.yml

- name: PGBouncer | Check pgbouncer version
  shell: pgbouncer --version | grep -i pgbouncer | awk '{if($2 == "version") print $3; else print $2 }'
  register: pgbouncer_installed_version
  tags:
    - deploy

- set_fact:
    pgbouncer_include_supported: "{{ pgbouncer_installed_version.stdout | version_compare('1.7', operator='ge', strict=True) }}"
  tags:
    - deploy

- include: configure_old.yml
  when: "not {{ pgbouncer_include_supported }}"

- include: configure_new.yml
  when: "{{ pgbouncer_include_supported }}"

- name: PGBouncer | Start pgbouncer service
  service:
    name: pgbouncer
    state: started
  tags:
    - deploy

- name: PGBouncer | Reload pgbouncer service
  service:
    name: pgbouncer
    state: reloaded
  when: pgbouncer_conf_changed.changed == True or pgbouncer_auth_changed.changed == True or pgbouncer_auth_users_results.changed == True
  tags:
    - deploy

- include: monitoring.yml
  tags: monitoring
